### ISSUE TITLE
Power on issue on Dyson Fan

### ISSUE THREAD

**Issue by yuetaika-cell** [cmgrayb/hass-dyson#199]
Hello, 

I installed the version 0.23.0 intergation and using Dyson Cloud account to auto discovery the Dyson Fan (Dyson Pure Hot+Cool Link™ purifier fan heater (HP02)) to Home assistant. But I hitted a strange issue when I power on the Fan even Heat mode or Cool mode.

The issue is Power on the fan in Heat mode / Cool mode, It will auto change to power off mode after 3-5 second in my home assistant display page but the Dyson Fan is working normally in Heat mode / Cool mode, then I also chekced in myDyson app is working normally with correct mode.

**Comment by cmgrayb** [comment]
Thank you for reporting this issue!  The team has identified that in certain less expected device states, the climate state was defaulting to Off.  In v0.23.1-beta.1, this behavior has been changed to only set the state to Off if the state is reported as off, leaving the mode in its current state and logging to debug channel when this situation occurs.

If you could, please try downloading v0.23.1-beta.1 and let us know if this change addresses your issue.  You may do so by going into the integration in HACS, selecting the Redownload option, and selecting the version you wish to download.  You may revert to the public/stable release by repeating this task, but not specifying a version.

If the issue persists, please enable debug logging in the integration: 

- menu/... 
- Select Enable Debug Logging 
- reproduce the issue
- disable debug logging in the same menu
- download file offered

Please ensure that you search for any serial numbers or credentials and replace them with a redaction before posting the debug log here.  We do not need or want them, and we want to ensure your information remains safe.

**Comment by cmgrayb** [comment]
Thank you for the debug log, it has provided an additional clue to the issue.  According to the log, the HP02 does not return the "fpwr" key expected on state-change messages, which we were expecting to use to update power state.  We have added a fallback to check "fnst" (fan state) on devices missing fpwr in state messages in v0.23.1-beta.2.  Can you download the latest beta and let us know if your experience is improved please?

**Comment by cmgrayb** [comment]
Thank you for your continued patience.  We have addressed the invalid humidity value format when the device returns "OFF", as well as normalized the power state between the climate and fan objects in v0.23.1-beta.3.  Please let us know if this improves your experience.

**Comment by yuetaika-cell** [comment]
I have upgraded to version 0.23.1-beta.4. Now I can use the Fan mode to power on the fan but climate mode is still have issue (auto change to power off after few second) even Heat Mode or Cool Mode.

<img width="305" height="257" alt="Image" src="https://github.com/user-attachments/assets/46c430e1-c128-4791-a1c0-1a933085b76c" />

<img width="296" height="327" alt="Image" src="https://github.com/user-attachments/assets/c835f0ed-21e2-494a-b148-1c613b5f1266" />

[log_20260103_v3.txt](https://github.com/user-attachments/files/24414253/log_20260103_v3.txt)

**Comment by yuetaika-cell** [comment]
Issue has been resloved, I can use Home assistant to power on with Cool mode / Heat mode.

Confirmed the version 0.23.1-beta.5 can fix the power issue of Dyson Pure Hot+Cool Link™ purifier fan heater (HP02).
