### ISSUE TITLE
Feature: Heater Support

### ISSUE THREAD

**Issue by cmgrayb** [cmgrayb/hass-dyson#46]
### Heater Support

- **Identify heater capability name**: Currently commented out pending real device testing
- **Add temperature sensors**: sensors for heater capable devices
- **Add climate platform**: climate platform required for HVAC control of heater
- **Files to update**: 
     - `sensor.py` - uncomment and implement carbon filter sensors
     - `climate.py` - uncomment and implement HVAC controls

**Comment by cmgrayb** [comment]
## Help Wanted!

We have all of the information required to create the sensors and attributes for heater devices.

What we need from the community is:

- Device Category
- Device Capabilities

With this information, we will be able to match up the sensors and attributes already created to add support for your device type!

How you can help:

We have a python script [dyson_api_device_scan.py](https://github.com/cmgrayb/libdyson-rest/blob/main/examples/dyson_api_device_scan.py) you can run which will output only non-sensitive information about your devices.  We need you to post just the category and capabilities sections in this thread, please.

Don't trust a random python script on the internet?  I wouldn't either.  Feel free to run the script through whatever analysis you like before you use it, and if you find a problem, let us know!  We want to keep our software as safe and bug free for the user as possible!  

We can also use the information from [opendyson](https://github.com/libdyson-wg/opendyson), who has been around for a lot longer than we have.

Thank you in advance, and we hope you like the integration!

**Comment by cmgrayb** [comment]
Good news!  Users no longer have to use an external tool to gather the information required!

As of v0.17.0, we have a Home Assistant Action available after adding a cloud account which can output the sanitized data we require for bug fixes and feature requests.  The new Action is called `Get Cloud Devices`.  If you already have a cloud account configured, the service will be available to you as soon as you update!  If you prefer to stay entirely local but still want to help, you can create a cloud account and deselect `Poll for new devices` to disable Home Assistant device discovery.  You will then have access to the cloud API through the Actions without using the cloud to control your device!  If you want to use this to create your manually devices, you can do that too!  Follow the same instructions, and use `Get Cloud Devices` without sanitized data to get all of the information required to create a manual device.  When you're done, you can delete the cloud account and keep your manually created devices!

Thank you in advance to everyone who can help make this integration amazing, we look forward to working with you!

**Comment by andrzejf1994** [comment]
Hi, 

I have a Dyson HP09 and the integration correctly discovers sensors and control entities.
However, no matter which communication mode I use on the device, nothing gets triggered in or by Home Assistant.
For example, the fan entity shows up, but after a refresh it switches to off, even though the physical fan is still running.
This means the entity states do not reflect the actual device state.
Happy to provide more logs if needed – thanks for your work on this integration!

Here is the sanitized output from the *Get Cloud Devices* action:

```yaml
account_email: "***HIDDEN***"
total_devices: 1
devices:
  - serial_number: "***HIDDEN***"
    name: Sypialnia
    product_type: 527KK
    device_category:
      - ec
    capabilities:
      - AdvanceOscillationDay1
      - Scheduling
      - EnvironmentalData
      - ExtendedAQ
      - ChangeWifi
    model: HP09
    mqtt_prefix: 527K
    connection_category: lecAndWifi
    setup_status: cloud_device
sanitized: true

**Comment by cmgrayb** [comment]
We are now up to v0.19.0-beta.6 as of today, and most heater controls should now be working.  If someone from this thread could try it out and let us know what is and is not working for you, it would be greatly appreciated!

**Comment by wisehalvdan** [comment]
<img width="1008" height="2244" alt="Image" src="https://github.com/user-attachments/assets/ed8a83d7-c909-4137-b431-2e24ce70676f" />

Temperature still only available as sensor not as a control in any way.

**Comment by andrzejf1994** [comment]
Hi,
I’ve updated to the latest beta, but I still don’t see a climate entity for my HP09 - it simply isn’t being created.
The entity that _wisehalvdan_ showed in the screenshot is actually just the fan entity, not a climate one.

Also, the fan entity on my side doesn’t switch the airflow direction (forward vs backward), so that part of the control is also missing.

**Comment by cmgrayb** [comment]
@andrzejf1994 - good catch on fan direction.  v0.19.0-beta.10 should hopefully address that issue as well.

**Comment by cmgrayb** [comment]
v0.19.0-beta.14 is now released.

fix: initialize _attr_hvac_mode with climate entity
fix: platform setup should now occur after capability refinement, allowing heaters to be detected through MQTT for cloud-discovered devices
fix: skip warning in logs when device is deleted
fix: merge pm2.5, pm10, formaldehyde sensors with "r" versions taking priority

Let us know if there is any improvement

**Comment by cmgrayb** [comment]
Tonight's beta is v0.19.0-beta.15.  Release notes are [here](https://github.com/cmgrayb/hass-dyson/releases/tag/v0.19.0-beta.15).

We do not expect it to be the last before 0.19.0 release day, so let us know what else we can fix please.
